package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Band <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface Band extends WrappedIndividual {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasBandIdentification
     */
     
    /**
     * Gets all property values for the hasBandIdentification property.<p>
     * 
     * @returns a collection of values for the hasBandIdentification property.
     */
    Collection<? extends BandIdentification> getHasBandIdentification();

    /**
     * Checks if the class has a hasBandIdentification property value.<p>
     * 
     * @return true if there is a hasBandIdentification property value.
     */
    boolean hasHasBandIdentification();

    /**
     * Adds a hasBandIdentification property value.<p>
     * 
     * @param newHasBandIdentification the hasBandIdentification property value to be added
     */
    void addHasBandIdentification(BandIdentification newHasBandIdentification);

    /**
     * Removes a hasBandIdentification property value.<p>
     * 
     * @param oldHasBandIdentification the hasBandIdentification property value to be removed.
     */
    void removeHasBandIdentification(BandIdentification oldHasBandIdentification);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
