package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: BandIdentification <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface BandIdentification extends WrappedIndividual {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasBandName
     */
     
    /**
     * Gets all property values for the hasBandName property.<p>
     * 
     * @returns a collection of values for the hasBandName property.
     */
    Collection<? extends Object> getHasBandName();

    /**
     * Checks if the class has a hasBandName property value.<p>
     * 
     * @return true if there is a hasBandName property value.
     */
    boolean hasHasBandName();

    /**
     * Adds a hasBandName property value.<p>
     * 
     * @param newHasBandName the hasBandName property value to be added
     */
    void addHasBandName(Object newHasBandName);

    /**
     * Removes a hasBandName property value.<p>
     * 
     * @param oldHasBandName the hasBandName property value to be removed.
     */
    void removeHasBandName(Object oldHasBandName);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
