package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: BoxedGeographicRegion <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface BoxedGeographicRegion extends GeographicRegion {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLeftLongitude
     */
     
    /**
     * Gets all property values for the hasLeftLongitude property.<p>
     * 
     * @returns a collection of values for the hasLeftLongitude property.
     */
    Collection<? extends Object> getHasLeftLongitude();

    /**
     * Checks if the class has a hasLeftLongitude property value.<p>
     * 
     * @return true if there is a hasLeftLongitude property value.
     */
    boolean hasHasLeftLongitude();

    /**
     * Adds a hasLeftLongitude property value.<p>
     * 
     * @param newHasLeftLongitude the hasLeftLongitude property value to be added
     */
    void addHasLeftLongitude(Object newHasLeftLongitude);

    /**
     * Removes a hasLeftLongitude property value.<p>
     * 
     * @param oldHasLeftLongitude the hasLeftLongitude property value to be removed.
     */
    void removeHasLeftLongitude(Object oldHasLeftLongitude);



    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLowerLatitude
     */
     
    /**
     * Gets all property values for the hasLowerLatitude property.<p>
     * 
     * @returns a collection of values for the hasLowerLatitude property.
     */
    Collection<? extends Object> getHasLowerLatitude();

    /**
     * Checks if the class has a hasLowerLatitude property value.<p>
     * 
     * @return true if there is a hasLowerLatitude property value.
     */
    boolean hasHasLowerLatitude();

    /**
     * Adds a hasLowerLatitude property value.<p>
     * 
     * @param newHasLowerLatitude the hasLowerLatitude property value to be added
     */
    void addHasLowerLatitude(Object newHasLowerLatitude);

    /**
     * Removes a hasLowerLatitude property value.<p>
     * 
     * @param oldHasLowerLatitude the hasLowerLatitude property value to be removed.
     */
    void removeHasLowerLatitude(Object oldHasLowerLatitude);



    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasRightLongitude
     */
     
    /**
     * Gets all property values for the hasRightLongitude property.<p>
     * 
     * @returns a collection of values for the hasRightLongitude property.
     */
    Collection<? extends Object> getHasRightLongitude();

    /**
     * Checks if the class has a hasRightLongitude property value.<p>
     * 
     * @return true if there is a hasRightLongitude property value.
     */
    boolean hasHasRightLongitude();

    /**
     * Adds a hasRightLongitude property value.<p>
     * 
     * @param newHasRightLongitude the hasRightLongitude property value to be added
     */
    void addHasRightLongitude(Object newHasRightLongitude);

    /**
     * Removes a hasRightLongitude property value.<p>
     * 
     * @param oldHasRightLongitude the hasRightLongitude property value to be removed.
     */
    void removeHasRightLongitude(Object oldHasRightLongitude);



    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasUpperLatitude
     */
     
    /**
     * Gets all property values for the hasUpperLatitude property.<p>
     * 
     * @returns a collection of values for the hasUpperLatitude property.
     */
    Collection<? extends Object> getHasUpperLatitude();

    /**
     * Checks if the class has a hasUpperLatitude property value.<p>
     * 
     * @return true if there is a hasUpperLatitude property value.
     */
    boolean hasHasUpperLatitude();

    /**
     * Adds a hasUpperLatitude property value.<p>
     * 
     * @param newHasUpperLatitude the hasUpperLatitude property value to be added
     */
    void addHasUpperLatitude(Object newHasUpperLatitude);

    /**
     * Removes a hasUpperLatitude property value.<p>
     * 
     * @param oldHasUpperLatitude the hasUpperLatitude property value to be removed.
     */
    void removeHasUpperLatitude(Object oldHasUpperLatitude);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
