package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ContainerFormat <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface ContainerFormat extends Format {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasPayloadFormat
     */
     
    /**
     * Gets all property values for the hasPayloadFormat property.<p>
     * 
     * @returns a collection of values for the hasPayloadFormat property.
     */
    Collection<? extends PayloadFormat> getHasPayloadFormat();

    /**
     * Checks if the class has a hasPayloadFormat property value.<p>
     * 
     * @return true if there is a hasPayloadFormat property value.
     */
    boolean hasHasPayloadFormat();

    /**
     * Adds a hasPayloadFormat property value.<p>
     * 
     * @param newHasPayloadFormat the hasPayloadFormat property value to be added
     */
    void addHasPayloadFormat(PayloadFormat newHasPayloadFormat);

    /**
     * Removes a hasPayloadFormat property value.<p>
     * 
     * @param oldHasPayloadFormat the hasPayloadFormat property value to be removed.
     */
    void removeHasPayloadFormat(PayloadFormat oldHasPayloadFormat);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
