package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: DateRange <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface DateRange extends Duration {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEndDate
     */
     
    /**
     * Gets all property values for the hasEndDate property.<p>
     * 
     * @returns a collection of values for the hasEndDate property.
     */
    Collection<? extends Date> getHasEndDate();

    /**
     * Checks if the class has a hasEndDate property value.<p>
     * 
     * @return true if there is a hasEndDate property value.
     */
    boolean hasHasEndDate();

    /**
     * Adds a hasEndDate property value.<p>
     * 
     * @param newHasEndDate the hasEndDate property value to be added
     */
    void addHasEndDate(Date newHasEndDate);

    /**
     * Removes a hasEndDate property value.<p>
     * 
     * @param oldHasEndDate the hasEndDate property value to be removed.
     */
    void removeHasEndDate(Date oldHasEndDate);


    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasStartDate
     */
     
    /**
     * Gets all property values for the hasStartDate property.<p>
     * 
     * @returns a collection of values for the hasStartDate property.
     */
    Collection<? extends Date> getHasStartDate();

    /**
     * Checks if the class has a hasStartDate property value.<p>
     * 
     * @return true if there is a hasStartDate property value.
     */
    boolean hasHasStartDate();

    /**
     * Adds a hasStartDate property value.<p>
     * 
     * @param newHasStartDate the hasStartDate property value to be added
     */
    void addHasStartDate(Date newHasStartDate);

    /**
     * Removes a hasStartDate property value.<p>
     * 
     * @param oldHasStartDate the hasStartDate property value to be removed.
     */
    void removeHasStartDate(Date oldHasStartDate);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
