package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Date <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface Date extends Instant {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDateTime
     */
     
    /**
     * Gets all property values for the hasDateTime property.<p>
     * 
     * @returns a collection of values for the hasDateTime property.
     */
    Collection<? extends Object> getHasDateTime();

    /**
     * Checks if the class has a hasDateTime property value.<p>
     * 
     * @return true if there is a hasDateTime property value.
     */
    boolean hasHasDateTime();

    /**
     * Adds a hasDateTime property value.<p>
     * 
     * @param newHasDateTime the hasDateTime property value to be added
     */
    void addHasDateTime(Object newHasDateTime);

    /**
     * Removes a hasDateTime property value.<p>
     * 
     * @param oldHasDateTime the hasDateTime property value to be removed.
     */
    void removeHasDateTime(Object oldHasDateTime);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
