package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PRISMModelling <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface PRISMModelling extends Modelling {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasAssociatedWith
     */
     
    /**
     * Gets all property values for the wasAssociatedWith property.<p>
     * 
     * @returns a collection of values for the wasAssociatedWith property.
     */
    Collection<? extends Processor> getWasAssociatedWith();

    /**
     * Checks if the class has a wasAssociatedWith property value.<p>
     * 
     * @return true if there is a wasAssociatedWith property value.
     */
    boolean hasWasAssociatedWith();

    /**
     * Adds a wasAssociatedWith property value.<p>
     * 
     * @param newWasAssociatedWith the wasAssociatedWith property value to be added
     */
    void addWasAssociatedWith(Processor newWasAssociatedWith);

    /**
     * Removes a wasAssociatedWith property value.<p>
     * 
     * @param oldWasAssociatedWith the wasAssociatedWith property value to be removed.
     */
    void removeWasAssociatedWith(Processor oldWasAssociatedWith);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
