package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Projection <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface Projection extends WrappedIndividual {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEPSGCode
     */
     
    /**
     * Gets all property values for the hasEPSGCode property.<p>
     * 
     * @returns a collection of values for the hasEPSGCode property.
     */
    Collection<? extends Integer> getHasEPSGCode();

    /**
     * Checks if the class has a hasEPSGCode property value.<p>
     * 
     * @return true if there is a hasEPSGCode property value.
     */
    boolean hasHasEPSGCode();

    /**
     * Adds a hasEPSGCode property value.<p>
     * 
     * @param newHasEPSGCode the hasEPSGCode property value to be added
     */
    void addHasEPSGCode(Integer newHasEPSGCode);

    /**
     * Removes a hasEPSGCode property value.<p>
     * 
     * @param oldHasEPSGCode the hasEPSGCode property value to be removed.
     */
    void removeHasEPSGCode(Integer oldHasEPSGCode);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
