package edu.utep.cybershare.elseweb.ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SpeciesOccurrenceLayer <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public interface SpeciesOccurrenceLayer extends Layer {

    /* ***************************************************
     * Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#containsFeatureSet
     */
     
    /**
     * Gets all property values for the containsFeatureSet property.<p>
     * 
     * @returns a collection of values for the containsFeatureSet property.
     */
    Collection<? extends FeatureSet> getContainsFeatureSet();

    /**
     * Checks if the class has a containsFeatureSet property value.<p>
     * 
     * @return true if there is a containsFeatureSet property value.
     */
    boolean hasContainsFeatureSet();

    /**
     * Adds a containsFeatureSet property value.<p>
     * 
     * @param newContainsFeatureSet the containsFeatureSet property value to be added
     */
    void addContainsFeatureSet(FeatureSet newContainsFeatureSet);

    /**
     * Removes a containsFeatureSet property value.<p>
     * 
     * @param oldContainsFeatureSet the containsFeatureSet property value to be removed.
     */
    void removeContainsFeatureSet(FeatureSet oldContainsFeatureSet);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
