package edu.utep.cybershare.elseweb.ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Band
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BAND.<p>
     * 
     */
    public static final OWLClass CLASS_BAND = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Band"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#BandIdentification
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BANDIDENTIFICATION.<p>
     * 
     */
    public static final OWLClass CLASS_BANDIDENTIFICATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#BandIdentification"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#BoxedGeographicRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOXEDGEOGRAPHICREGION.<p>
     * 
     */
    public static final OWLClass CLASS_BOXEDGEOGRAPHICREGION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#BoxedGeographicRegion"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Characteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_CHARACTERISTIC = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Characteristic"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#ContainerFormat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTAINERFORMAT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTAINERFORMAT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#ContainerFormat"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#DataBand
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATABAND.<p>
     * 
     */
    public static final OWLClass CLASS_DATABAND = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#DataBand"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#DatasetManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATASETMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_DATASETMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#DatasetManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Date
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATE.<p>
     * 
     */
    public static final OWLClass CLASS_DATE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Date"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#DateRange
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATERANGE.<p>
     * 
     */
    public static final OWLClass CLASS_DATERANGE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#DateRange"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Duration
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DURATION.<p>
     * 
     */
    public static final OWLClass CLASS_DURATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Duration"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Entity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_ENTITY = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Entity"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#FeatureSet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEATURESET.<p>
     * 
     */
    public static final OWLClass CLASS_FEATURESET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#FeatureSet"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#FileManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FILEMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_FILEMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#FileManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Format
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORMAT.<p>
     * 
     */
    public static final OWLClass CLASS_FORMAT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Format"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#GeographicRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEOGRAPHICREGION.<p>
     * 
     */
    public static final OWLClass CLASS_GEOGRAPHICREGION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#GeographicRegion"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#GeospatialDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GEOSPATIALDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_GEOSPATIALDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#GeospatialDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Instant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INSTANT.<p>
     * 
     */
    public static final OWLClass CLASS_INSTANT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Instant"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Layer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LAYER.<p>
     * 
     */
    public static final OWLClass CLASS_LAYER = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Layer"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#MetadataFormat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METADATAFORMAT.<p>
     * 
     */
    public static final OWLClass CLASS_METADATAFORMAT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#MetadataFormat"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#NamedGeographicRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NAMEDGEOGRAPHICREGION.<p>
     * 
     */
    public static final OWLClass CLASS_NAMEDGEOGRAPHICREGION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#NamedGeographicRegion"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#OGCResponseManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OGCRESPONSEMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_OGCRESPONSEMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#OGCResponseManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#OGCServiceManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OGCSERVICEMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_OGCSERVICEMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#OGCServiceManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#PayloadFormat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PAYLOADFORMAT.<p>
     * 
     */
    public static final OWLClass CLASS_PAYLOADFORMAT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#PayloadFormat"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Projection
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECTION.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECTION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Projection"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#RasterDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RASTERDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_RASTERDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#RasterDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#ServiceManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICEMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICEMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#ServiceManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Theme
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THEME.<p>
     * 
     */
    public static final OWLClass CLASS_THEME = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Theme"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#TimePeriod
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIMEPERIOD.<p>
     * 
     */
    public static final OWLClass CLASS_TIMEPERIOD = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#TimePeriod"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Unit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UNIT.<p>
     * 
     */
    public static final OWLClass CLASS_UNIT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#Unit"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#VectorDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VECTORDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_VECTORDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#VectorDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WCSDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_WCSDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WCSMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_WCSMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSResponse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WCSRESPONSE.<p>
     * 
     */
    public static final OWLClass CLASS_WCSRESPONSE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSResponse"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSResponseManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WCSRESPONSEMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_WCSRESPONSEMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WCSResponseManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WFSDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_WFSDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WFSMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_WFSMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSResponse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WFSRESPONSE.<p>
     * 
     */
    public static final OWLClass CLASS_WFSRESPONSE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSResponse"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSResponseManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WFSRESPONSEMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_WFSRESPONSEMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#WFSResponseManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Air
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AIR.<p>
     * 
     */
    public static final OWLClass CLASS_AIR = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Air"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Amount
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AMOUNT.<p>
     * 
     */
    public static final OWLClass CLASS_AMOUNT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Amount"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#AtmosphericFeature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATMOSPHERICFEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_ATMOSPHERICFEATURE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#AtmosphericFeature"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ConvertASCIIToTIFF
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONVERTASCIITOTIFF.<p>
     * 
     */
    public static final OWLClass CLASS_CONVERTASCIITOTIFF = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ConvertASCIIToTIFF"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ConvertedDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONVERTEDDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_CONVERTEDDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ConvertedDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DataBandProcessing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATABANDPROCESSING.<p>
     * 
     */
    public static final OWLClass CLASS_DATABANDPROCESSING = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DataBandProcessing"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DatasetManipulationSoftware
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATASETMANIPULATIONSOFTWARE.<p>
     * 
     */
    public static final OWLClass CLASS_DATASETMANIPULATIONSOFTWARE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DatasetManipulationSoftware"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DatasetProcessing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATASETPROCESSING.<p>
     * 
     */
    public static final OWLClass CLASS_DATASETPROCESSING = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DatasetProcessing"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DewPointTemperature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEWPOINTTEMPERATURE.<p>
     * 
     */
    public static final OWLClass CLASS_DEWPOINTTEMPERATURE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DewPointTemperature"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Download
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOWNLOAD.<p>
     * 
     */
    public static final OWLClass CLASS_DOWNLOAD = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Download"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DownloadedMODISDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOWNLOADEDMODISDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_DOWNLOADEDMODISDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DownloadedMODISDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DownloadedPRISMDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOWNLOADEDPRISMDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_DOWNLOADEDPRISMDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#DownloadedPRISMDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#EcologicalCommunity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ECOLOGICALCOMMUNITY.<p>
     * 
     */
    public static final OWLClass CLASS_ECOLOGICALCOMMUNITY = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#EcologicalCommunity"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ExtractAndReproject
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTRACTANDREPROJECT.<p>
     * 
     */
    public static final OWLClass CLASS_EXTRACTANDREPROJECT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ExtractAndReproject"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ExtractedDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXTRACTEDDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_EXTRACTEDDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ExtractedDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Index
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INDEX.<p>
     * 
     */
    public static final OWLClass CLASS_INDEX = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Index"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#MODISDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MODISDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_MODISDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#MODISDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#MODISMeasurement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MODISMEASUREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_MODISMEASUREMENT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#MODISMeasurement"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Measurement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASUREMENT.<p>
     * 
     */
    public static final OWLClass CLASS_MEASUREMENT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Measurement"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Modelling
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MODELLING.<p>
     * 
     */
    public static final OWLClass CLASS_MODELLING = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Modelling"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ModellingAgent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MODELLINGAGENT.<p>
     * 
     */
    public static final OWLClass CLASS_MODELLINGAGENT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ModellingAgent"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Mosaic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOSAIC.<p>
     * 
     */
    public static final OWLClass CLASS_MOSAIC = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Mosaic"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#MosaicDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOSAICDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_MOSAICDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#MosaicDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PRISMDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRISMDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_PRISMDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PRISMDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PRISMModelling
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRISMMODELLING.<p>
     * 
     */
    public static final OWLClass CLASS_PRISMMODELLING = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PRISMModelling"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Precipitation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRECIPITATION.<p>
     * 
     */
    public static final OWLClass CLASS_PRECIPITATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Precipitation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Processing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSING.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSING = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Processing"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Processor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSOR.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSOR = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Processor"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Publish
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PUBLISH.<p>
     * 
     */
    public static final OWLClass CLASS_PUBLISH = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Publish"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PublishedMODISDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PUBLISHEDMODISDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_PUBLISHEDMODISDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PublishedMODISDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PublishedPRISMDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PUBLISHEDPRISMDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_PUBLISHEDPRISMDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#PublishedPRISMDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISCHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_RGISCHARACTERISTIC = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISCharacteristic"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISDataBand
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISDATABAND.<p>
     * 
     */
    public static final OWLClass CLASS_RGISDATABAND = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISDataBand"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_RGISENTITY = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISEntity"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISPrepublishedRasterDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISPREPUBLISHEDRASTERDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_RGISPREPUBLISHEDRASTERDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISPrepublishedRasterDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_RGISUNIT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISUnit"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISWCSDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISWCSDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_RGISWCSDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISWCSDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISWCSManifestation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RGISWCSMANIFESTATION.<p>
     * 
     */
    public static final OWLClass CLASS_RGISWCSMANIFESTATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#RGISWCSManifestation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Reproject
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPROJECT.<p>
     * 
     */
    public static final OWLClass CLASS_REPROJECT = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Reproject"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ReprojectedDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPROJECTEDDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_REPROJECTEDDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#ReprojectedDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_SENSOR = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Sensor"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#SurfaceLayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SURFACELAYER.<p>
     * 
     */
    public static final OWLClass CLASS_SURFACELAYER = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#SurfaceLayer"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Temperature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPERATURE.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPERATURE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Temperature"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#TerrestrialFeature
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TERRESTRIALFEATURE.<p>
     * 
     */
    public static final OWLClass CLASS_TERRESTRIALFEATURE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#TerrestrialFeature"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Vegetation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETATION.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETATION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#Vegetation"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#LifemapperAlgorithm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LIFEMAPPERALGORITHM.<p>
     * 
     */
    public static final OWLClass CLASS_LIFEMAPPERALGORITHM = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#LifemapperAlgorithm"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#LifemapperParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LIFEMAPPERPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_LIFEMAPPERPARAMETER = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#LifemapperParameter"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#LifemapperSoftware
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LIFEMAPPERSOFTWARE.<p>
     * 
     */
    public static final OWLClass CLASS_LIFEMAPPERSOFTWARE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#LifemapperSoftware"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#ParameterDescription
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETERDESCRIPTION.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETERDESCRIPTION = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#ParameterDescription"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#ParameterDescriptions
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETERDESCRIPTIONS.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETERDESCRIPTIONS = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#ParameterDescriptions"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#Species
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIES.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIES = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#Species"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#SpeciesOccurrenceDataset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESOCCURRENCEDATASET.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESOCCURRENCEDATASET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#SpeciesOccurrenceDataset"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#SpeciesOccurrenceLayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESOCCURRENCELAYER.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESOCCURRENCELAYER = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#SpeciesOccurrenceLayer"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#SpeciesOccurrenceSet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESOCCURRENCESET.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESOCCURRENCESET = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#SpeciesOccurrenceSet"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingAlgorithm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESMODELLINGALGORITHM.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESMODELLINGALGORITHM = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingAlgorithm"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingParameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESMODELLINGPARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESMODELLINGPARAMETER = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingParameter"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingParameters
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESMODELLINGPARAMETERS.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESMODELLINGPARAMETERS = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingParameters"));

    /* ***************************************************
     * Class http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingSoftware
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIESMODELLINGSOFTWARE.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIESMODELLINGSOFTWARE = factory.getOWLClass(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#SpeciesModellingSoftware"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#containsFeatureSet
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSFEATURESET.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSFEATURESET = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#containsFeatureSet"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#coversRegion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COVERSREGION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COVERSREGION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#coversRegion"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#coversTimePeriod
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COVERSTIMEPERIOD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COVERSTIMEPERIOD = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#coversTimePeriod"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#encodedInFormat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ENCODEDINFORMAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ENCODEDINFORMAT = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#encodedInFormat"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#encodingOfCharacteristic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ENCODINGOFCHARACTERISTIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ENCODINGOFCHARACTERISTIC = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#encodingOfCharacteristic"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasBandIdentification
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBANDIDENTIFICATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBANDIDENTIFICATION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasBandIdentification"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDataBand
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDATABAND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDATABAND = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDataBand"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDATE = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDate"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEndDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASENDDATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASENDDATE = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEndDate"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasGeospatialProjection
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASGEOSPATIALPROJECTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASGEOSPATIALPROJECTION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasGeospatialProjection"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLayer
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLAYER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLAYER = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLayer"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasManifestation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMANIFESTATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMANIFESTATION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasManifestation"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasPayloadFormat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPAYLOADFORMAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPAYLOADFORMAT = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasPayloadFormat"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasStartDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTARTDATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTARTDATE = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasStartDate"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasTheme
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTHEME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTHEME = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasTheme"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasUnits
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASUNITS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASUNITS = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasUnits"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#representsEntity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REPRESENTSENTITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REPRESENTSENTITY = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#representsEntity"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hadInput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HADINPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HADINPUT = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hadInput"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hadInputBandID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HADINPUTBANDID.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HADINPUTBANDID = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hadInputBandID"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasAssociatedWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WASASSOCIATEDWITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WASASSOCIATEDWITH = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasAssociatedWith"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasMeasuredBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WASMEASUREDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WASMEASUREDBY = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasMeasuredBy"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasModelledBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WASMODELLEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WASMODELLEDBY = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasModelledBy"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasOutputBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WASOUTPUTBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WASOUTPUTBY = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasOutputBy"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasPublishedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WASPUBLISHEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WASPUBLISHEDBY = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#wasPublishedBy"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#describesBehaviorOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DESCRIBESBEHAVIOROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DESCRIBESBEHAVIOROF = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#describesBehaviorOf"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasOccurrenceOfSpecies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASOCCURRENCEOFSPECIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASOCCURRENCEOFSPECIES = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasOccurrenceOfSpecies"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasParameterDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPARAMETERDESCRIPTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPARAMETERDESCRIPTION = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasParameterDescription"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#controlsBehaviorOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTROLSBEHAVIOROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTROLSBEHAVIOROF = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#controlsBehaviorOf"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#hasParameterMember
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPARAMETERMEMBER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPARAMETERMEMBER = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#hasParameterMember"));

    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#implementedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IMPLEMENTEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IMPLEMENTEDIN = factory.getOWLObjectProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#implementedIn"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasBandName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASBANDNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASBANDNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasBandName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasCapabilitiesDocumentURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCAPABILITIESDOCUMENTURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCAPABILITIESDOCUMENTURL = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasCapabilitiesDocumentURL"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDateTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDATETIME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDATETIME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasDateTime"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEPSGCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEPSGCODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEPSGCODE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEPSGCode"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasFileDownloadURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASFILEDOWNLOADURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASFILEDOWNLOADURL = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasFileDownloadURL"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLandingPageURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLANDINGPAGEURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLANDINGPAGEURL = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLandingPageURL"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLatitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLATITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLATITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLatitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLeftLongitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLEFTLONGITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLEFTLONGITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLeftLongitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLongitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLONGITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLONGITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLongitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLowerLatitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOWERLATITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOWERLATITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLowerLatitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasMaximumValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMAXIMUMVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMAXIMUMVALUE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasMaximumValue"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasMinimumValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMINIMUMVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMINIMUMVALUE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasMinimumValue"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasNoDataValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNODATAVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNODATAVALUE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasNoDataValue"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasNumberOfOccurrences
     */
     
    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasOccurrenceSetID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASOCCURRENCESETID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASOCCURRENCESETID = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasOccurrenceSetID"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasResolution
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRESOLUTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRESOLUTION = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasResolution"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasRightLongitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRIGHTLONGITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRIGHTLONGITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasRightLongitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasUpperLatitude
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUPPERLATITUDE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUPPERLATITUDE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasUpperLatitude"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#getJSONCapabilitiesDigestURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GETJSONCAPABILITIESDIGESTURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASJSONCAPABILITIESDIGESTURL = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hasJSONCapabilitiesDigestURL"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hasProcessorName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASPROCESSORNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASPROCESSORNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-edac.owl#hasProcessorName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#boundToValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BOUNDTOVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BOUNDTOVALUE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#boundToValue"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasAlgorithmCode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALGORITHMCODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALGORITHMCODE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasAlgorithmCode"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasCanonicalName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCANONICALNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCANONICALNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasCanonicalName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasDefaultValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDEFAULTVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDEFAULTVALUE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasDefaultValue"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasLowerBoundInclusive
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLOWERBOUNDINCLUSIVE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLOWERBOUNDINCLUSIVE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasLowerBoundInclusive"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasNumberOfOccurrences
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNUMBEROFOCCURRENCES.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNUMBEROFOCCURRENCES = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasNumberOfOccurrences"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasOccurrenceSetID
     */
     
    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasUpperBoundInclusive
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUPPERBOUNDINCLUSIVE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUPPERBOUNDINCLUSIVE = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-lifemapper.owl#hasUpperBoundInclusive"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#hasAlgorithmName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASALGORITHMNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASALGORITHMNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#hasAlgorithmName"));

    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#hasParameterName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASPARAMETERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASPARAMETERNAME = factory.getOWLDataProperty(IRI.create("http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-modelling.owl#hasParameterName"));


}
