package edu.utep.cybershare.elseweb.ontology.impl;

import edu.utep.cybershare.elseweb.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultContainerFormat <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */
public class DefaultContainerFormat extends WrappedIndividualImpl implements ContainerFormat {

    public DefaultContainerFormat(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasPayloadFormat
     */
     
    public Collection<? extends PayloadFormat> getHasPayloadFormat() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASPAYLOADFORMAT,
                                               DefaultPayloadFormat.class);
    }

    public boolean hasHasPayloadFormat() {
	   return !getHasPayloadFormat().isEmpty();
    }

    public void addHasPayloadFormat(PayloadFormat newHasPayloadFormat) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASPAYLOADFORMAT,
                                       newHasPayloadFormat);
    }

    public void removeHasPayloadFormat(PayloadFormat oldHasPayloadFormat) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASPAYLOADFORMAT,
                                          oldHasPayloadFormat);
    }


}
