package edu.utep.cybershare.elseweb.ontology.impl;

import edu.utep.cybershare.elseweb.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLayer <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */
public class DefaultLayer extends WrappedIndividualImpl implements Layer {

    public DefaultLayer(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#containsFeatureSet
     */
     
    public Collection<? extends FeatureSet> getContainsFeatureSet() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CONTAINSFEATURESET,
                                               DefaultFeatureSet.class);
    }

    public boolean hasContainsFeatureSet() {
	   return !getContainsFeatureSet().isEmpty();
    }

    public void addContainsFeatureSet(FeatureSet newContainsFeatureSet) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CONTAINSFEATURESET,
                                       newContainsFeatureSet);
    }

    public void removeContainsFeatureSet(FeatureSet oldContainsFeatureSet) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CONTAINSFEATURESET,
                                          oldContainsFeatureSet);
    }


}
