package edu.utep.cybershare.elseweb.ontology.impl;

import edu.utep.cybershare.elseweb.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultProjection <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */
public class DefaultProjection extends WrappedIndividualImpl implements Projection {

    public DefaultProjection(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasEPSGCode
     */
     
    public Collection<? extends Integer> getHasEPSGCode() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEPSGCODE, Integer.class);
    }

    public boolean hasHasEPSGCode() {
		return !getHasEPSGCode().isEmpty();
    }

    public void addHasEPSGCode(Integer newHasEPSGCode) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEPSGCODE, newHasEPSGCode);
    }

    public void removeHasEPSGCode(Integer oldHasEPSGCode) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASEPSGCODE, oldHasEPSGCode);
    }


}
