package edu.utep.cybershare.elseweb.ontology.impl;

import edu.utep.cybershare.elseweb.ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultBoxedGeographicRegion <br>
 * @version generated on Thu Feb 13 13:45:51 GMT-07:00 2014 by nick
 */
public class DefaultBoxedGeographicRegion extends WrappedIndividualImpl implements BoxedGeographicRegion {

    public DefaultBoxedGeographicRegion(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLeftLongitude
     */
     
    public Collection<? extends Object> getHasLeftLongitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEFTLONGITUDE, Object.class);
    }

    public boolean hasHasLeftLongitude() {
		return !getHasLeftLongitude().isEmpty();
    }

    public void addHasLeftLongitude(Object newHasLeftLongitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEFTLONGITUDE, newHasLeftLongitude);
    }

    public void removeHasLeftLongitude(Object oldHasLeftLongitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLEFTLONGITUDE, oldHasLeftLongitude);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasLowerLatitude
     */
     
    public Collection<? extends Object> getHasLowerLatitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLOWERLATITUDE, Object.class);
    }

    public boolean hasHasLowerLatitude() {
		return !getHasLowerLatitude().isEmpty();
    }

    public void addHasLowerLatitude(Object newHasLowerLatitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLOWERLATITUDE, newHasLowerLatitude);
    }

    public void removeHasLowerLatitude(Object oldHasLowerLatitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASLOWERLATITUDE, oldHasLowerLatitude);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasRightLongitude
     */
     
    public Collection<? extends Object> getHasRightLongitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASRIGHTLONGITUDE, Object.class);
    }

    public boolean hasHasRightLongitude() {
		return !getHasRightLongitude().isEmpty();
    }

    public void addHasRightLongitude(Object newHasRightLongitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASRIGHTLONGITUDE, newHasRightLongitude);
    }

    public void removeHasRightLongitude(Object oldHasRightLongitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASRIGHTLONGITUDE, oldHasRightLongitude);
    }


    /* ***************************************************
     * Data Property http://ontology.cybershare.utep.edu/ELSEWeb/elseweb-data.owl#hasUpperLatitude
     */
     
    public Collection<? extends Object> getHasUpperLatitude() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUPPERLATITUDE, Object.class);
    }

    public boolean hasHasUpperLatitude() {
		return !getHasUpperLatitude().isEmpty();
    }

    public void addHasUpperLatitude(Object newHasUpperLatitude) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUPPERLATITUDE, newHasUpperLatitude);
    }

    public void removeHasUpperLatitude(Object oldHasUpperLatitude) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASUPPERLATITUDE, oldHasUpperLatitude);
    }


}
